<?php
class Validator
{
    /**
     * stores the data from the $_POST/$_GET superglobal
     */
    protected $data = [];

    /**
     * Registers the validation methods
     */
    protected $registered_validators = ['id'     => 'isIdValid',
                                        'lic_no' => 'isLicenseNumValid',
                                        'fname'  => 'isNameValid',
                                        'lname'   => 'isNameValid',
                                        'uname'   => 'isIdValid',
                                        'empid'   => 'isIdValid',
                                        'passwd'  => 'isPasswordValid',
                                        'email'       => 'isEmailValid',
                                        'telephone'   => 'isTelephoneValid',
                                        'telephone2'   => 'isTelephoneValid',
                                        'addr1'     => 'isAddressValid',
                                        'addr2'     => 'isAddressValid',
                                        'parish'    => null,
                                        'add_driver'  =>  null,
                                        'MAX_FILE_SIZE' => null,
                                        'cancel_add'  =>  null,
                                        'validation_done_by_js' =>  null,
                                    ];
    
    /**
     * Stores errors messages generated by the validator
     */
    protected $errors = [];

    /**
     * Takes the $_POST superglobal and initializes the $data property
     */
    public function __construct(array $post_data)
    {
        if (empty($post_data)) {
            trigger_error('Validator initialized with empty data set', E_USER_WARNING);
        }
        $this->data = $post_data;
    }

    /**
     * Performs the validation on each data item stored in the $data property
     */
    public function validate() : bool
    {
        // Validation was done on the client side so no need to validate here
        if (isset($this->data['validation_done_by_js']) && 
            ($this->data['validation_done_by_js'])) {
                return true;
        }

        if (empty($this->data)) {
            trigger_error('No data received for validation', E_USER_WARNING);
            return true;
        }
        foreach($this->data as $key=>$value) {
            // if there is no registered validation method
            if (!array_key_exists($key, $this->registered_validators)) {
                $warning_msg = 'Form field ' . $key . ' has no registered validator method. Validation not done';
                trigger_error($warning_msg, E_USER_WARNING);
                //$this->setErrors($warning_msg);
            }
            else {
                // get the registered validator
                $validator = $this->registered_validators[$key];
                // if validator method is null, no validation is required for that variable
                if (is_null($validator)) {
                    continue;
                }
                // check to make sure the method exists before calling it. Issue a warning if it doesn't
                if (!method_exists($this, $validator)) {
                    $warning_msg = 'Form field ' . $key . ' has a registered validator but no corresponding validator method. Validation not done';
                    trigger_error($warning_msg, E_USER_WARNING);
                    //$this->setErrors($warning_msg);
                }
                else {
                    // remember that each validator should update the $errors property
                    // if the data is invalid
                    $this->$validator($value);
                }
            }
        }
        return (empty($this->errors) ? true : false);
    }

    /**
     * Returns the error messages generated by the validator
     * @return array
     */
    public function getErrors() : array
    {
        return $this->errors;
    }

    /**
     * Internal method to update the error message property
     * @param $err_msg  The generated error message
     */
    protected function setErrors(string $field_name, string $err_msg)
    {
        // abort with an error message if no err_msg was passed :-)
        if (empty($err_msg)) {
            trigger_error('Cannot create an empty error message', E_USER_ERROR);
        }
        if (empty($field_name)) {
            trigger_error('Invalid field name used. Cannot be empty', E_USER_ERROR);
        }
        $this->errors[$field_name] = $err_msg;
    }

    /**
     * The validator for the national id field
     */
    protected function isIdValid(string $id) : bool
    {
        $first_six = '';
        $last_four = '';
        
        if (empty($id)) {
            $this->setErrors('id', 'No value given for the national id');
            return false;
        }

        if (strstr($id, '-')) {
            // split the id into its corresponding parts since it's not empty and has a hyphen
            list($first_six, $last_four) = explode('-', $id);
        }
        else {
            $this->setErrors('id', 'Hyphen required for the national id number');
            return false;
        }
        
        if (empty($first_six) || empty($last_four)) {
            $this->setErrors('id', 'Format invalid - part of the id is missing');
            return false;
        }

        if (!ctype_digit($first_six) || !ctype_digit($last_four)) {
            $this->setErrors('id', 'Format invalid - part of the id does not contain numbers');
            return false;
        }

        if (strlen($first_six) <> 6 || strlen($last_four) <> 4) {
            $this->setErrors('id', 'Format invalid - part(s) of the id has an incorrect number of digits.');
            return false;
        }
        return true;
    }

    /**
     * Validates the license number
     */
    protected function isLicenseNumValid(string $licenseno) : bool
    {
        if (empty($licenseno)) {
            $this->setErrors('lic_no', 'Invalid license number. Cannot be empty');
            return false;
        }

        if (strlen($licenseno) <> 15) {
            $this->setErrors('lic_no', 'Invalid license number length');
            return false;
        }

        if (!ctype_digit($licenseno)) {
            $this->setErrors('lic_no', 'License number must contain only digits');
            return false;
        }

        // validating the date
        $last_eight = substr($licenseno, 7);
        $yyyy = substr($last_eight, 0, 4);
        $mm = substr($last_eight, 4, 2);
        $dd = substr($last_eight, 6);
        if (!checkdate($mm, $dd, $yyyy)) {
            $this->setErrors('lic_no', 'Invalid date');
            return false;
        }
        $today = date_create();
        $license_date = date_create("$yyyy-$mm-$dd");
        $interval = date_diff($today, $license_date);
        // creating the right conditional is left as an exercise for you to complete
        $years = $interval->format('%y');
        if ( $years < 16) {
            $this->setErrors('lic_no', 'License number less than 16 years ago ' . $years);
            return false;
        }
        return true;
}   

    protected function isTelephoneValid($tel)
    {
        return true;
    }

    protected function isPasswordValid()
    {
        if(empty($passwd))
        {
            $this->setErrors('passwd', 'This field must be filled.');
            return false;
        }
        else
        {
            if((strlen($passwd) < 8) && (strlen($passwd) >16) )
            {
            $this->setErrors('passwd', 'Invalid Password Format');
            return false;
            }
            else
            {
                return true;
            }
        }
    }

    protected function isNameValid(string $name)
    {
        return true;
    }

    protected function isAddressValid($address)
    {
        return true;
    }

    protected function isEmailValid(string $email)
    {
        if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $this->setErrors('email', 'Invalid email format');
            return false;
        }
        return true;
    }
}